# Generated by Django 2.2.5 on 2019-09-27 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0003_auto_20190925_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Post',
        ),
    ]
